export const GET_STUDENTS_PENDING = "GET_STUDENTS_PENDING";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const ADD_STUDENTS_PENDING = "ADD_STUDENTS_PENDING";
export const ADD_STUDENTS_SUCCESS = "ADD_STUDENTS_SUCCESS";
export const ADD_STUDENTS_FAILURE = "ADD_STUDENTS_FAILURE";
