export const GET_ATTENDANCE_PENDING = "GET_ATTENDANCE_PENDING";
export const GET_ATTENDANCE_SUCCESS = "GET_ATTENDANCE_SUCCESS";
export const GET_ATTENDANCE_FAILURE = "GET_ATTENDANCE_FAILURE";

export const ADD_ATTENDANCE_PENDING = "ADD_ATTENDANCE_PENDING";
export const ADD_ATTENDANCE_SUCCESS = "ADD_ATTENDANCE_SUCCESS";
export const ADD_ATTENDANCE_FAILURE = "ADD_ATTENDANCE_FAILURE";
