export const GET_LEAVE_PENDING = "GET_LEAVE_PENDING";
export const GET_LEAVE_SUCCESS = "GET_LEAVE_SUCCESS";
export const GET_LEAVE_FAILURE = "GET_LEAVE_FAILURE";

export const ADD_LEAVE_PENDING = "ADD_LEAVE_PENDING";
export const ADD_LEAVE_SUCCESS = "ADD_LEAVE_SUCCESS";
export const ADD_LEAVE_FAILURE = "ADD_LEAVE_FAILURE";


export const EDIT_LEAVE_PENDING = "EDIT_LEAVE_PENDING";
export const EDIT_LEAVE_SUCCESS = "EDIT_LEAVE_SUCCESS";
export const EDIT_LEAVE_FAILURE = "EDIT_LEAVE_FAILURE";